let v1 = 1;
console.log(typeof(0));
let v2 = 2;
console.log(typeof(3.14));
let v3 = 3;
console.log(typeof(Infinity));
let v4 = 4;
console.log(typeof(NaN));
let v5 = 5;
console.log(typeof(true));
let v6 = 6;
console.log(typeof(4>1));
let v7 = 7;
console.log(typeof("texto"));
let v8 = 8;
console.log(typeof("É tetra"+1994));
let v9 = 9;
console.log(typeof(Symbol("id")));
let v10 = 10;
console.log(typeof(Date));
let v11 = 11;
console.log(typeof(String));
let v12 = 12;
console.log(typeof([1,2,3,4]));
let v13 = 13;
console.log(typeof(null));
let v14 = 14;
console.log(typeof(undefined));
let v15 = 15; 
console.log(typeof(alert));
